Configuration initiale:
  icon: "icon-wrench"
  pages:
    setup/installation: "Installation"
    setup/configuration: "Configuration"

CMS:
  icon: "icon-magic"
  pages:
    cms/themes: "Thèmes"
    cms/pages: "Pages"
    cms/partials: "Partiels"
    cms/layouts: "Maquettes"
    cms/content: "Blocs de contenus"
    cms/components: "Composants"
    cms/mediamanager: "Gestionnaire des Médias"
    markup/templating: "Guide de balisage@"

AJAX:
  icon: "icon-bolt"
  pages:
    ajax/introduction: "Introduction"
    ajax/handlers: "Gestionnaire d'évènements"
    ajax/update-partials: "Mises à jours de partiels"
    ajax/attributes-api: "API des attributs de données"
    ajax/javascript-api: "API JavaScript"
    ajax/extras: "Fonctionnalités supplémentaires"

Thèmes:
  icon: "icon-picture"
  pages:
    themes/development: "Développement des thèmes"

#Plugins:
#  icon: "icon-puzzle-piece"
#  pages:
#    plugin/registration: "Registration"
#    plugin/updates: "Version history"
#    plugin/components: "Building components"
#    plugin/settings: "Settings & Config"
#    plugin/localization: "Localization"
#    plugin/scheduling: "Task scheduling"
#    plugin/extending: "Extending plugins"

Backend:
  icon: "icon-desktop"
  pages:
    backend/controllers-ajax: "Contrôleurs et AJAX"
#    backend/views-partials: "Views & Partials"
#    backend/widgets: "Widgets"
#    backend/forms: "Forms"
#    backend/lists: "Lists"
#    backend/relations: "Relations"
#    backend/reorder: "Sorting records"
#    backend/import-export: "Importing & Exporting"
#    backend/users: "Users & Permissions"
#    ui: "User interface guide@"

Base de données:
  icon: "icon-hdd"
  pages:
    #    database/basics: "Basic usage"
    #    database/structure: "Structure"
    #    database/query: "Queries"
    #    database/model: "Models"
    #    database/relations: "Relationships"
        database/attachments: "Fichiers joints"
    #    database/collection: "Collections"
    #    database/mutators: "Mutators"
    #    database/serialization: "Serialization"
    #    database/traits: "Traits"
    database/behaviors: "Comportements"

#Services:
#  icon: "icon-gears"
#  pages:
#    services/application: "Application"
#    services/behaviors: "Behaviors"
#    services/cache: "Cache"
#    services/collections: "Collections"
#    services/error-log: "Errors & Logging"
#    services/events: "Events"
#    services/html: "Forms & Html"
#    services/filesystem-cdn: "Filesystem / CDN"
#    services/hashing-encryption: "Hashing & Encryption"
#    services/helpers: "Helpers"
#    services/mail: "Mail"
#    services/pagination: "Pagination"
#    services/parser: "Parser"
#    services/queues: "Queues"
#    services/request-input: "Request & Input"
#    services/response-view: "Response & View"
#    services/router: "Router"
#    services/session: "Session"
#    services/validation: "Validation"

Console:
  icon: "icon-terminal"
  pages:
    #    console/commands: "Command list"
    console/scaffolding: "Patrons"
#    console/development: "Development"

#"API Docs@":
#  page: api

#Extras:
#  icon: "icon-question-sign"
#  pages:
#    help/unit-testing: "Unit Testing"
#    help/using-composer: "Using Composer"
#    ../help/guidelines/quality: "Quality guidelines@"
#    ../help/guidelines/developer: "Developer guide@"
